site_name: Google-Group-Admin-API Documentation
site_description: A Python library for managing Google Cloud Platform groups via Google Workspace Directory API
site_author: Martial Wafo
site_url: https://github.com/martialo12/Google-Group-Admin-API

theme:
  name: readthedocs

plugins:
  - search
  - mkdocstrings:
      watch:
        - google_workspace_group_manager

nav:
  - Home: index.md
  - API Reference:
      - GoogleWorkspaceConfig: config.md
      - GoogleWorkspaceGroupManager: group_manager.md

markdown_extensions:
  - admonition
  - codehilite
